admin:
  username: admin
  password: admin

game:
  mode: classic
  round_time: 60
  start_time: 2024-09-07 11:00:00
  timezone: Asia/Bangkok

  default_score: 10000
  flag_lifetime: 5
  game_hardness: 10.0
  inflation: true

tasks:
  - checker: art/checker.py
    checker_timeout: 30
    checker_type: hackerdom
    gets: 1
    name: art
    places: 1
    puts: 1
  - checker: back-to-basic/checker.py
    checker_timeout: 30
    checker_type: hackerdom
    gets: 1
    name: back-to-basic
    places: 1
    puts: 1
  - checker: burvesigner/checker.py
    checker_timeout: 30
    checker_type: hackerdom
    gets: 1
    name: burvesigner
    places: 1
    puts: 1
  - checker: crawlback/checker.py
    checker_timeout: 30
    checker_type: hackerdom
    gets: 1
    name: crawlback
    places: 1
    puts: 1
  - checker: gemas-fetcher/checker.py
    checker_timeout: 30
    checker_type: hackerdom
    gets: 1
    name: gemas-fetcher
    places: 1
    puts: 1
  - checker: gemas-notes/checker.py
    checker_timeout: 30
    checker_type: hackerdom
    gets: 1
    name: gemas-notes
    places: 1
    puts: 1
  - checker: hirnfick/checker.py
    checker_timeout: 30
    checker_type: hackerdom
    gets: 1
    name: hirnfick
    places: 1
    puts: 1
  - checker: pasta/checker.py
    checker_timeout: 30
    checker_type: hackerdom
    gets: 1
    name: pasta
    places: 1
    puts: 1
  - checker: s3/checker.py
    checker_timeout: 30
    checker_type: hackerdom
    gets: 1
    name: s3
    places: 1
    puts: 1
  - checker: xl/checker.py
    checker_timeout: 30
    checker_type: hackerdom
    gets: 1
    name: xl
    places: 1
    puts: 1

teams:
  - ip: 10.104.0.3
    name: "HCS - Kos0ng Fans Club"
  - ip: 10.104.0.4
    name: "HCS - murid mentor"
  - ip: 10.104.0.5
    name: "HCS - GaadaHandleCrypto"
  - ip: 10.104.0.6
    name: "Guest"